### ISSUE TITLE
Proposal: improve support for tags, add categories

### ISSUE THREAD

**Issue by StephanieDClark** [washingtonpost/ans-schema#87]
**Problem**
ANS Tags do not support wordpress categories

**Proposed Solution**
Add to utils/tag.json:
 - slug = tag or category slug, e.g. 'my-category-slug'
 - text = tag or category name ~~(currently listed in spec as "tag")~~
 - description = tag or category description
 - additional_properties = (same as elsewhere, used for non-standard metadata)

**Example**
```tags: [
{
_id: "DGBTWSJS2BHNTPWLVVUYPM6T6E",
  text: "My Category Name",
  additional_properties: {wordpress_type: "category"},
  slug:  "my-category-name",
  description: "My superfab category"
},
{
_id: "AMKDOSHIJ5FYVJS5UASQZ2G2CY",
text: "My Tag Name",
  additional_properties: {wordpress_type: "tag"},
slug: "my-tag-name",
description: "My unparalleled tag"
}
]
```

**Question**
Currently, tags have two properties, on the api output: _id and "tag".  Am I misreading the spec when it appears that the properties should be _id and "text"?

**Comment by gengel** [comment]
You are not misreading the tag.json schema; As currently implemented, it allows any fields in the tag object, which is why `tag` appears on the objects.  I would add to your proposal:

* Change the tag object to forbid non-spec properties
* Standardize on "tag" since that field seems to already be in use; add some logic to the 0.5.7->0.5.8 upverter to copy any data in `text` into `tag` if present
* Add the other fields you describe (`additional_properties`, `slug`, `description` )

**Comment by gengel** [comment]
Actually glancing around the partners, it looks like `text` is generally being used, so maybe we stick to that and figure out why `tag` is getting populated
